name: 'Trivy Docker Scan'
description: 'Scans a docker image for vulnerabilities using Trivy'
inputs:
  image-name:
    description: 'Name of the image to scan'
    required: true
  image-tag:
    description: 'Tag of the image to scan'
    required: true
  github-token:
    description: 'GitHub Token for commenting on PRs'
    required: true
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: Run Trivy vulnerability scanner
      id: trivy_run
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: '${{ inputs.image-name }}:${{ inputs.image-tag }}'
        format: 'table'
        output: 'trivy-results.txt'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Print Trivy Results
      shell: bash
      run: |
        if [ -f trivy-results.txt ]; then
          cat trivy-results.txt
        fi

    - name: Post Trivy Results to PR Comment
      if: github.event_name == 'pull_request' && steps.trivy_run.outcome == 'failure'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ -s trivy-results.txt ]; then
          echo '```text' > trivy-comment.md
          cat trivy-results.txt >> trivy-comment.md
          echo '```' >> trivy-comment.md
          gh pr comment ${{ github.event.pull_request.number }} --body-file trivy-comment.md
        fi

    - name: Fail if vulnerabilities found
      if: steps.trivy_run.outcome == 'failure'
      shell: bash
      run: |
        echo "Vulnerabilities found! Failing the build."
        exit 1
